# Generated by Django 5.0.3 on 2024-04-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatid', models.IntegerField(primary_key=True, serialize=False)),
                ('chat_title', models.CharField(max_length=400)),
                ('chat_content', models.TextField()),
                ('chat_sender', models.CharField(max_length=100)),
                ('chat_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
