# Generated by Django 5.0.3 on 2024-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogid', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=400)),
                ('blog_content', models.TextField()),
                ('blog_image', models.ImageField(null=True, upload_to='blog_image')),
                ('blog_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
