# Generated by Django 5.0.3 on 2024-04-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
