# Generated by Django 3.2.25 on 2024-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
